app:
  s3:
    bucket: ${AWS_S3_BUCKET}

spring:
  config:
    import: aws-parameterstore:/payment-app/prod/

  datasource:
    url: ${DB_URL}/${DB_NAME}?rewriteBatchedStatements=true&cachePrepStmts=true&useServerPrepStmts=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      timeout: 5s

logging:
  level:
    root: warn

jwt:
  secret: ${JWT_SECRET}

oauth2:
  redirect-url: ${OAUTH2_REDIRECT_URL}

api:
  base-url: